export const GET_FURNITURE = "GET_FURNITURE";
export const GET_LOADING = "GET_LOADING";
export const GET_ERROR = "GET_ERROR";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const LOGIN_SIGNUP_SUCCESS = "LOGIN_SIGNUP_SUCCESS";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const ORDER_DONE = "ORDER_DONE";